### ISSUE TITLE
Append Error

### ISSUE THREAD

**Issue by fugitivers** [vladimirvivien/gowfs#13]
<html><head><title>Apache Tomcat/6.0.41 - Error report</title><style></style> </head><body><h1>HTTP Status 400 - Data upload requests must have content-type set to 'application/octet-stream'</h1><HR size="1" noshade="noshade"><p><b>type</b> Status report</p><p><b>message</b> <u>Data upload requests must have content-type set to 'application/octet-stream'</u></p><p><b>description</b> <u>The request sent by the client was syntactically incorrect.</u></p><HR size="1" noshade="noshade"><h3>Apache Tomcat/6.0.41</h3></body></html>
invalid character '<' looking for beginning of value

**Comment by vladimirvivien** [comment]
@fugitivers thanks for reporting this.  What version of Hadoop/hdfs were you using ? Was this a stand-alone deployment of webfs ?

**Comment by fugitivers** [comment]
thanks,Hadoop version is release 2.6.0 , I add code 'application/octet-stream' with ‘append’ method,success
